"use client";

import { CalendarDays, ChevronDown, MapPin, Minus, Plus, Sparkles, Users } from "lucide-react";
import { useState } from "react";

export function PlannerForm({ onCreated }: { onCreated: (destination: string) => void }) {
  const [travelers, setTravelers] = useState(2);
  const [interests, setInterests] = useState(["Culture", "Food"]);
  const [destination, setDestination] = useState("Kyoto, Japan");
  const options = ["Beaches", "Nature", "Adventure", "Wellness", "Nightlife"];

  return <div className="max-w-4xl">
    <div className="mb-8"><p className="mb-2 text-sm font-semibold text-blue-600 dark:text-blue-300">NEW JOURNEY</p><h1 className="text-4xl font-bold tracking-[-0.04em] text-slate-950 dark:text-white">Where do you want to go?</h1><p className="mt-3 max-w-xl text-slate-500 dark:text-slate-400">Tell us a little about your next escape. Our planning engine will shape the details around you.</p></div>
    <div className="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_24px_80px_-48px_rgba(15,23,42,0.3)] sm:p-8 dark:border-slate-800 dark:bg-slate-900">
      <label className="block"><span className="mb-2 block text-sm font-semibold">Destination</span><div className="relative"><MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-blue-600" size={18} /><input value={destination} onChange={(e) => setDestination(e.target.value)} className="h-14 w-full rounded-xl border border-slate-200 bg-slate-50 pl-12 pr-4 text-base font-medium outline-none transition focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-500/10 dark:border-slate-700 dark:bg-slate-950 dark:focus:bg-slate-950" /></div></label>
      <div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-semibold">Dates</span><div className="relative"><CalendarDays className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input className="h-14 w-full rounded-xl border border-slate-200 bg-slate-50 pl-12 pr-4 text-sm font-medium outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 dark:border-slate-700 dark:bg-slate-950" value="Oct 12 — Oct 18, 2026" readOnly /></div></label><div><span className="mb-2 block text-sm font-semibold">Travelers</span><div className="flex h-14 items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-4 dark:border-slate-700 dark:bg-slate-950"><div className="flex items-center gap-3"><Users size={18} className="text-slate-400" /><span className="text-sm font-medium">{travelers} adults</span></div><div className="flex gap-1"><button aria-label="Remove traveler" onClick={() => setTravelers(Math.max(1, travelers - 1))} className="grid size-8 place-items-center rounded-lg border border-slate-200 bg-white text-slate-500 hover:border-blue-300 dark:border-slate-700 dark:bg-slate-900"><Minus size={14} /></button><button aria-label="Add traveler" onClick={() => setTravelers(travelers + 1)} className="grid size-8 place-items-center rounded-lg border border-slate-200 bg-white text-slate-500 hover:border-blue-300 dark:border-slate-700 dark:bg-slate-900"><Plus size={14} /></button></div></div></div></div>
      <div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-semibold">Total budget</span><div className="flex h-14 items-center rounded-xl border border-slate-200 bg-slate-50 px-4 dark:border-slate-700 dark:bg-slate-950"><span className="mr-3 text-slate-400">₹</span><input className="w-full bg-transparent text-sm font-semibold outline-none" defaultValue="1,50,000" /><span className="text-xs text-slate-400">INR</span></div></label><label className="block"><span className="mb-2 block text-sm font-semibold">Travel pace</span><div className="relative"><select className="h-14 w-full appearance-none rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-medium outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-950"><option>Balanced — see it all</option><option>Slow — room to breathe</option><option>Fast — make it count</option></select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" size={17} /></div></label></div>
      <div><span className="mb-3 block text-sm font-semibold">What are you into?</span><div className="flex flex-wrap gap-2">{[...interests, ...options].map((interest, index) => <button key={interest} onClick={() => setInterests(interests.includes(interest) ? interests.filter((item) => item !== interest) : [...interests, interest])} className={`rounded-full border px-4 py-2 text-sm font-medium transition ${interests.includes(interest) ? "border-blue-600 bg-blue-600 text-white shadow-md shadow-blue-600/20" : "border-slate-200 bg-white text-slate-500 hover:border-blue-300 dark:border-slate-700 dark:bg-slate-950"}`}>{interest}{index < 2 && interests.includes(interest) ? "  ×" : ""}</button>)}</div></div>
      <div className="flex flex-col items-start justify-between gap-4 border-t border-slate-100 pt-5 sm:flex-row sm:items-center dark:border-slate-800"><p className="text-xs text-slate-400">Your plan will be generated in under a minute.</p><button onClick={() => onCreated(destination)} className="flex h-12 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:-translate-y-0.5 hover:bg-blue-700"><Sparkles size={16} />Generate itinerary</button></div>
    </div>
  </div>;
}
